[build]
publish = "dist"
command = "pnpm run build"

[build.environment]
NODE_VERSION = "20"
PLAYWRIGHT_BROWSERS_PATH = "0"

[[redirects]]
from = "2023-08-19"
to = "https://talks.mini-ghost.dev/2023/open-source-adventure/"
status = 301

[[redirects]]
from = "/2023/open-source-adventure/*"
to = "/2023/open-source-adventure/index.html"
status = 200

[[redirects]]
from = "2024-03-19"
to = "https://talks.mini-ghost.dev/2024/javascript-asynchronous-patterns/"
status = 301

[[redirects]]
from = "/2024/javascript-asynchronous-patterns/*"
to = "/2024/javascript-asynchronous-patterns/index.html"
status = 200

[[redirects]]
from = "2024-10-30"
to = "https://talks.mini-ghost.dev/2024/qlieer-book-club-october/"
status = 301

[[redirects]]
from = "/2024/qlieer-book-club-october/*"
to = "/2024/qlieer-book-club-october/index.html"
status = 200

[[redirects]]
from = "2025-11-13"
to = "https://talks.mini-ghost.dev/2025/source-code-for-vue-ch7-and-ch8/"
status = 301

[[redirects]]
from = "/2025/source-code-for-vue-ch7-and-ch8/*"
to = "/2025/source-code-for-vue-ch7-and-ch8/index.html"
status = 200

[[redirects]]
from = "2025-11-29"
to = "https://talks.mini-ghost.dev/2025/jsdc-vite-adventure/"
status = 301

[[redirects]]
from = "/2025/jsdc-vite-adventure/*"
to = "/2025/jsdc-vite-adventure/index.html"
status = 200

[[redirects]]
from = "/"
to = "https://mini-ghost.dev/talks"
status = 302
